# Generated by Django 4.2.5 on 2023-10-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drinks", old_name="drink", new_name="drink_name",
        ),
    ]
